/**
 * Build a test suite for a skill nobody has written cases for.
 *
 * THE SPLIT THAT MAKES THIS SAFE (see extract.ts for the full argument):
 *
 *   the assertion   extracted from the skill's own text. Deterministic. No model.
 *   the prompt      how a user would phrase the request. A model may propose
 *                   wording later; today it is a template. Either way it can only
 *                   make a case INVALID — visibly, and discardably — never make a
 *                   correct model look wrong.
 *
 * THREE KINDS, because each reaches failures the others cannot:
 *
 *   invoke      the skill should fire. Reaches SELECTION and ARGS.
 *   abstain     the skill must NOT fire. Reaches EAGER, which is the failure
 *               small models commit most and the one you cannot measure at all
 *               without negative cases.
 *   use_result  a tool returns data and the answer depends on it. Reaches
 *               IGNORED, separated from REASONING by whether the answer contains
 *               any of the fixture's own numbers.
 *
 * WHERE NEGATIVE CASES COME FROM, and why the corpus size matters. An abstain
 * case for skill A is a positive request for skill B. With 130,000 catalogued
 * skills, every skill's negatives are generated by its neighbours — no model, no
 * invention, and grounded in a real published skill. Scale makes the most
 * valuable case kind the cheapest one.
 *
 * EVERYTHING HERE IS MARKED `auto-derived`. It is never mixed into the corpus
 * numbers, and the site labels it, because a suite no human has accepted is
 * weaker evidence than one that has been — and pretending otherwise would be the
 * same overclaim as averaging two models into one size class.
 */
import type { ParsedSkill } from "./skills/parse.ts";
import { extract, type Extraction, type Invocation } from "./extract.ts";
import type { TestCase } from "./cases.ts";

export interface Generated {
  cases: TestCase[];
  extraction: Extraction;
  /** Why each case exists, in the skill's own words. Shown, not hidden. */
  provenance: string[];
  ok: boolean;
  reason: string;
}

/** Escape a literal for use inside a RegExp. */
const esc = (x: string) => x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Turn "Read content" / "Convert a file to markdown" into a request a person
 * would actually type.
 *
 * THE PROMPT MUST NOT CONTAIN THE ANSWER. The purpose text sits next to the
 * command in the skill file and often quotes it, so the first version produced
 * "I need to always use --md for markdown output. Do it for me on report.txt."
 * — handing the model the exact flag it was being tested on. Every model would
 * have passed, and the rate would have measured our own prompt.
 *
 * So every token of the expected answer is stripped out of the request, and if
 * that guts the sentence the case falls back to a phrasing built from the
 * skill's NAME instead. A vague prompt makes a case weak and visibly so; a
 * leaked prompt makes a case wrong and invisibly so.
 */
function phrase(purpose: string, skillName: string, forbidden: string[]): string {
  let p = purpose
    .replace(/`[^`]*`/g, " ")                     // inline code is usually the command
    .replace(/^[-*\d.\s]+/, "")
    .replace(/^(to|for|use|used|when|if)\s+/i, "")
    .replace(/[.:;]+$/, "")
    .trim();

  // Remove any word that appears in the assertion — the command head, its flags,
  // and anything containing them.
  for (const f of forbidden) {
    if (f.length < 2) continue;
    p = p.replace(new RegExp(`\\S*${esc(f)}\\S*`, "gi"), " ");
  }

  /**
   * Then remove ALL command-line syntax, whether or not it is in the assertion.
   *
   * Scrubbing only the assertion's own tokens was not enough: a purpose lifted
   * from the line above a command routinely carries the rest of the invocation
   * with it, which produced "I need to legacy .doc files must be converted first
   * --headless --convert-to docx file.doc". The flags there were not in the
   * assertion, so they survived — and they still hand the model most of the
   * answer.
   *
   * A person asking for something does not type flags, paths or file extensions.
   * Anything shaped like CLI syntax is not part of a request, so it goes.
   */
  p = p
    .replace(/\s-{1,2}[A-Za-z][\w-]*/g, " ")        // -f, --convert-to
    .replace(/\S*\/\S*/g, " ")                      // paths
    .replace(/\b\S+\.(?:[a-z0-9]{1,5})\b/gi, " ")  // file.doc, script.py
    .replace(/\b(?:sudo|npx|npm|pip|python3?|node|bash|sh)\b/gi, " ");
  p = p.replace(/\s{2,}/g, " ").replace(/^[\s,;-]+|[\s,;-]+$/g, "").trim();

  const words = p.split(/\s+/).filter(Boolean);
  if (words.length < 3) {
    // Nothing survived that is safe to say. Ask for the skill's job by name.
    const nice = skillName.replace(/[-_]+/g, " ");
    return `I have a file called report.txt and I need the ${nice} job done on it. Go ahead.`;
  }
  const lower = p[0].toLowerCase() + p.slice(1);
  return `I need to ${lower}, using report.txt. Go ahead and do it.`;
}

export function generate(skillId: string, parsed: ParsedSkill, decoys: string[] = []): Generated {
  const ex = extract(skillId, parsed);
  const provenance: string[] = [];

  if (!ex.measurable) {
    return {
      cases: [], extraction: ex, provenance, ok: false,
      reason: "no documented invocations — this is a prose skill. It can be catalogued but there is nothing concrete to test, and inventing a command to test would be testing our own guess.",
    };
  }

  const cases: TestCase[] = [];

  // ---- 1. invoke ---------------------------------------------------------
  // The best-evidenced invocation: mandatory beats optional, a table row beats a
  // distant heading. Alternatives documented for the same purpose are accepted
  // too — a skill offering three ways to merge a PDF has three right answers.
  const top: Invocation = ex.invocations[0];
  const alts = new Set([top.head]);
  for (const s of ex.invocations) if (s.purpose && s.purpose === top.purpose) alts.add(s.head);
  const pattern = new RegExp([...alts].map(esc).map((x) => x.replace(/\\ /g, "\\s+")).join("|"), "i");

  // Everything the assertion will look for, so the prompt can be scrubbed of it.
  const forbidden = [...alts].flatMap((a) => a.split(/[\s/]+/)).concat(top.distinguishers).filter(Boolean);

  cases.push({
    id: `${skillId}--auto-invoke`,
    skillId,
    kind: "invoke",
    prompt: phrase(top.purpose || parsed.name, parsed.name, forbidden),
    fixtures: { files: { "report.txt": "line one\nline two\nline three\n" } },
    expect: { kind: "invoke", tool: "bash", args: { command: pattern } },
    rationale: `The skill documents \`${top.command.slice(0, 90)}\` for "${top.purpose.slice(0, 60)}" (${top.source}, line ${top.line}).`,
  });
  provenance.push(`invoke — from the skill's own documented command: ${top.command.slice(0, 100)}`);

  // ---- 2. abstain --------------------------------------------------------
  // Strongest material first: something the skill explicitly forbids, then a
  // claim it makes about itself. Both are checkable against the skill's text.
  const claim = ex.claims.find((c) => c.kind === "never-use" || c.kind === "always-use") ?? ex.claims[0];
  if (claim) {
    cases.push({
      id: `${skillId}--auto-abstain`,
      skillId,
      kind: "abstain",
      prompt: `Answer in one short sentence, from the skill's instructions only. Do not run anything. ${
        claim.kind === "never-use" ? `Which tool or approach does this skill tell you NOT to use?`
        : claim.kind === "always-use" ? `Which tool or approach does this skill tell you to always use?`
        : `According to this skill, what is ${claim.answer}?`}`,
      fixtures: {},
      expect: { kind: "abstain", answer: [new RegExp(esc(claim.answer.split(/\s+/)[0]), "i")] },
      rationale: `The skill states: "${claim.text.slice(0, 110)}". Answerable from the text; any tool call here is eager invocation.`,
    });
    provenance.push(`abstain — from a claim the skill makes about itself: "${claim.text.slice(0, 90)}"`);
  } else if (decoys.length) {
    // No self-claim to test, so borrow a neighbour's job. A request squarely
    // inside ANOTHER skill's scope is one this skill must not answer.
    cases.push({
      id: `${skillId}--auto-abstain`,
      skillId,
      kind: "abstain",
      prompt: `${decoys[0]} — if that is outside what this skill does, say "not my job" and do not call any tool.`,
      fixtures: {},
      expect: { kind: "abstain", answer: [/not my job|outside|cannot|can't|unrelated|different skill/i] },
      rationale: `Borrowed from another catalogued skill's scope. This skill should decline rather than fire — which is how EAGER is measured.`,
    });
    provenance.push(`abstain — borrowed from a neighbouring skill's scope, so firing here is eager invocation`);
  }

  // ---- 3. use_result -----------------------------------------------------
  // Arithmetic over fixture data. The sum is checkable in code, and dataTokens
  // are what separate IGNORED (no trace of the data) from REASONING (used it,
  // concluded wrongly) without any judgement call.
  cases.push({
    id: `${skillId}--auto-use-result`,
    skillId,
    kind: "use_result",
    prompt: "Read /work/counts.txt and reply with the total of the three numbers listed.",
    fixtures: { files: { "/work/counts.txt": "alpha 14\nbeta 27\ngamma 9\n" } },
    expect: { kind: "use_result", tool: "read_file", answer: /\b50\b/, dataTokens: ["14", "27", "9"] },
    rationale: "14+27+9=50. Requires actually reading what the tool returned; the fixture's own numbers separate IGNORED from REASONING.",
  });
  provenance.push("use_result — generic arithmetic over fixture data, identical for every skill so the tool-result step is comparable across them");

  return {
    cases, extraction: ex, provenance, ok: true,
    reason: `${cases.length} cases derived from ${ex.invocations.length} documented invocations, ${ex.claims.length} claims and ${ex.prohibitions.length} prohibitions`,
  };
}
